#!/bin/bash
args=""
for arg in "$@"; do args="$args,\"$arg\""; done
if [[ -z "$(command -v tscxxx)" ]]; then args="$args,\"-tsc=false\""; fi
args="[${args:1}]"
java -Xms16m -Xmx128m -Dargs="$args" -Dvertx.options.blockedThreadCheckInterval=16000 -Dvertx.options.maxEventLoopExecuteTime=600000000000 -jar sourcerer.jar
exit
jdk/bin/java -Xms8m -Xmx64m -jar sourcerer.jar -Dcfg=cfg.js -Dsrc=test.js -Dvertx.options.blockedThreadCheckInterval=16000 -Dvertx.options.maxEventLoopExecuteTime=600000000000
exit