#!/bin/bash

if [[ "$1" == "build" ]]; then
    mvn package clean
    exit
    #JAVA_HOME_0=$JAVA_HOME
    #export JAVA_HOME=jdk
    #mvn/bin/mvn package clean
    #export JAVA_HOME="$JAVA_HOME_0"
    #exit
fi

args=""
for arg in "$@"; do args="$args,\"$arg\""; done
if [[ -z "$(command -v tsc)" ]]; then args="$args,\"-tsc=false\""; fi
args="[${args:1}]"
java -Xms16m -Xmx128m -Dargs="$args" -Dvertx.options.blockedThreadCheckInterval=16000 -Dvertx.options.maxEventLoopExecuteTime=600000000000 -jar sourcerer.jar
exit
#jdk/bin/java -Xms8m -Xmx64m -jar sourcerer.jar -Dcfg=cfg.js -Dsrc=test.js -Dvertx.options.blockedThreadCheckInterval=16000 -Dvertx.options.maxEventLoopExecuteTime=600000000000
#exit